make importable
ELELAB/pyinteraph2 pull request #88
Opened 2022-11-21 13:33 UTC by frannerin

Added an `argsv` argument to the `main` function with `None` as a default, and passed this `argsv` to the `parser.parse_args(argsv)` function. This way, the `main` function can be imported and a list of arguments passed as if they were those on CLI (e.g., a list with `argsv=["-s", "protein.pdb", "-t", "traj_1.xtc", "-m"]`) to use PyInteraph2 programatically. With `argsv` being `None` as default, it ensures that when PyInteraph2 is called from the CLI the `parser.parse_args` function looks for `sys.argv` as always. See [here](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_args) how the first argument of `parse_args` is already `None` by default and it makes it use `sys.argv`.

2022-12-06 14:25 UTC, mtiberti requested changes
Hi,

thanks for this and sorry for the late reply. This is interesting - importing the main function could be useful for different reasons. It was never designed to be imported though (as you have seen)

I've tested this a bit and it can lead to unexpected outcomes in case e.g. arguments are not supplied correctly (it exits the interpreter altogether - which is not very good for troubleshooting or in general):

```
>>> from pyinteraph.main import main
>>> main()
ERROR: Topology and trajectory are required.
(pyinteraph-env) user@computer:~$
```

I think we need some more work to make this working properly,  I haven't looked into this in depth but for instance
  - overriding `exit` and `error` methods in `ArgumentParser`
  - checking if `__name__ == '__main__'` before exiting in other parts of the code and raising exceptions instead

if you want to give it a try feel welcome to - otherwise I'll try to help when possible

2022-12-17 21:45 UTC, frannerin commented
Hi, thanks for the feedback and your suggestions! I added a little workaround to handle the calls to the `exit` function when inside the interactive Python interpreter. It's probably not good practice and against many guidelines but it works hehe:

```
(pyinteraph-env) frann@TABLET-TLSBVHL4:~/pyinteraph2$ pyinteraph
ERROR: Topology and trajectory are required.
```

```
>>> from pyinteraph.main import main
>>> main()
ERROR: Topology and trajectory are required.
>>>
```

So far the workaround is only inside the `main` function of the `main` module, but I've seen that there are also calls to the `exit` function in other modules, and I don't know what would be the best way to have this workaround work on them too; copy and paste the code, have it run in the main namespace e.g. in the __init__ (don't know if that will work)... Let me know what you think!

2023-01-03 10:26 UTC, mtiberti commented
Hi again,

thank you.

I see your workaround - I think we want to look into something a bit more tailored. If `main()` fails inside another script, you do want it to raise an exception rather than just print a message (good it doesn't close the interpreter, at least :) ). I tried to find a more thorough solution in an example script, which seems to work as we would like:

```
import argparse

if __name__ != '__main__':
    class ArgumentParser(argparse.ArgumentParser):
        def error(self, message):
            self.exit(2, message)
        def exit(self, status=0, message=None):
            raise ValueError(message)
else:
    from argparse import ArgumentParser

def main(argsv=None):

    parser = ArgumentParser()

    parser.add_argument('number')

    args = parser.parse_args(argsv)

    try:
        number = int(args.number)
    except:
        raise TypeError("argument is not a number")

    print(f"number: {number}")

if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print(str(e) + "; Exiting...")
        exit(1)
```

Here I am:
  - subclassing `ArgumentParser` so that it doesn't exit in case the supplied arguments are not as expected - it raises an exception instead
  - raising an exception instead of `exit()`ing directly - this is useful if `main` is used in a script. Instead, if the script is run from the command line, we catch the exception and exit cleanly, providing a useful message on the terminal.

this looks like a reasonable solution to me, if you want to try and implement it in the PyInteraph `main()` and give it a test

2023-03-13 09:24 UTC, mtiberti commented
hi @frannerin , are you still interested in this? Otherwise I'm prone to close it

2023-03-23 08:32 UTC, closed without merging